name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/*.jar
