name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        architecture: 'x64'
    - name: Build with Maven
      run: |
        ./mvnw clean package -DskipTests
        # Create the deploy directory if it doesn't exist
        #mkdir -p deploy
        # Move the JAR file to the deploy directory
        #mv target/StudentManagement-0.0.1-SNAPSHOT.jar deploy/
    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: deploy/StudentManagement-0.0.1-SNAPSHOT.jar
